service: alc-registrants

frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: provided.al2023
  architecture: arm64
  region: us-west-2
  stage: prod
  environment:
    EVENTBRITE_TOKEN: ${ssm:eventbrite_token~true}

package:
 individually: true
 exclude:
   - ./**

functions:
  totalRegistrants:
    name: alc-registrants-total
    description: Gets and displays the total number of ALC registrants.
    handler: bootstrap
    package:
      artifact: bin/totalRegistrants.zip
    events:
      - http:
          path: alc-registrants/total
          method: get
    memorySize: 128
    timeout: 15
